---
extends: default

rules:
  # Allow 120 character line length
  line-length:
    max: 120
    allow-non-breakable-words: true

  # Require consistent spacing
  indentation:
    spaces: 2
    indent-sequences: true

  # Avoid trailing spaces
  trailing-spaces: enable

  # Require colons to have spaces after them
  colons:
    max-spaces-after: 1
    max-spaces-before: 0

  # Allow truthy values for GitHub Actions
  truthy:
    allowed-values: ['on', 'true', 'false']
    check-keys: false
