# ZMK Build Configuration
# This file defines which keyboards to build firmware for

include:
  - board: nice_nano
    shield: typeractive_corne_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: typeractive_corne_right
    snippet: studio-rpc-usb-uart