---
# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the include property using the format:
# include:
#   - board: nice_nano_v2
#     shield: corne_left
#   - board: nice_nano_v2
#     shield: corne_right

include:
  - board: nice_nano
    shield: crkbd_left
  - board: nice_nano
    shield: crkbd_right
